apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: backend
  name: backend
spec:
  replicas: 1
  selector:
    name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - image: docker.io/ganesh47/sbt_docker_k8s_backend:latest
          name: backend
          ports:
            - containerPort: 9500
              name: http
          resources:
            limits:
              cpu: 0.2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend
  name: backend
spec:
  ports:
    - port: 9500
      protocol: TCP
      targetPort: 9500
  selector:
    name: backend
